export const products = [
  {
    id: 1,
    brand: "Amber",
    name: "Amber Essence",
    price: 120,
    fragrance: "Woody",
    img: "/Pic/Amber/pic001.jpg",
    discount: 50,
    quantity: 10,
    description: "A warm woody fragrance that blends amber with subtle spice, evoking elegance and depth.",
    ingredients: ["Amber resin", "Sandalwood", "Cedar", "Spices"]
  },
  {
    id: 2,
    brand: "mera",
    name: "Mera Bloom",
    price: 85,
    fragrance: "Floral",
    img: "/Pic/mera/pic001.jpg",
    discount: null,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 3,
    brand: "The LAB",
    name: "Lab Classic",
    price: 150,
    fragrance: "Fresh",
    img: "/Pic/The_Lab_pic/pic001.jpg",
    discount: null,
    quantity: 0, 
    description: "A crisp fresh scent designed for modern minimalists, combining citrus and aquatic notes.",
    ingredients: ["Lemon zest", "Aquatic accord", "Green tea", "Musk"]
  },
  {
    id: 4,
    brand: "ROMYANA",
    name: "Romyana Pure",
    price: 95,
    fragrance: "Citrus",
    img: "/Pic/la_felle/pic001.jpg",
    discount: null,
   quantity: 10, 
    description: "Bright citrus tones that energize and uplift, perfect for daily wear.",
    ingredients: ["Orange peel", "Grapefruit", "Lime", "Cedarwood"]
  },
  {
    id: 5,
    brand: "TARO",
    name: "Taro Mist",
    price: 110,
    fragrance: "Oriental",
    img: "/Pic/Taro/pic001.jpg",
    discount: 20,
    quantity: 10, 
    description: "An oriental mist with exotic spices and deep resins, evoking mystery and allure.",
    ingredients: ["Cardamom", "Patchouli", "Vanilla", "Amber"]
  },

  {
    id: 6,
    brand: "AKA.BT",
    name: "AKA Gold",
    price: 130,
    fragrance: "Woody",
    img: "/Pic/AKA BT Perfume/pic001.jpg",
    discount: null,
    quantity: 10, 
    description: "Golden amber enriched with smoky woods, a timeless scent of sophistication.",
    ingredients: ["AKA resin", "Oud", "Sandalwood", "Tonka bean"]
  },
  {
    id: 7,
    brand: "mera",
    name: "Mera Shine",
    price: 90,
    fragrance: "Floral",
    img: "/Pic/mera/pic002.jpg",
    discount: null,
    quantity: 10, 
    description: "A radiant floral fragrance with sparkling notes of lily and peony.",
    ingredients: ["Lily", "Peony", "Rose water", "White musk"]
  },
  {
    id: 8,
    brand: "The LAB",
    name: "Lab Fresh",
    price: 140,
    fragrance: "Fresh",
    img: "/Pic/The_Lab_pic/pic002.jpg",
    discount: null,
    quantity: 10, 
    description: "Clean and invigorating, blending crisp citrus with herbal freshness.",
    ingredients: ["Mint", "Basil", "Lemon", "Sea breeze accord"]
  },
  {
    id: 9,
    brand: "ROMYANA",
    name: "Romyana Pure",
    price: 95,
    fragrance: "Citrus",
    img: "/Pic/la_felle/pic002.jpg",
    discount: null,
    quantity: 10, 
    description: "Pure citrus harmony with a touch of sweetness, uplifting and bright.",
    ingredients: ["Mandarin", "Bergamot", "Neroli", "Vetiver"]
  },
  {
    id: 10,
    brand: "TARO",
    name: "Taro Mist",
    price: 110,
    fragrance: "Oriental",
    img: "/Pic/Taro/pic002.jpg",
    discount: 20,
    quantity: 10, 
    description: "An oriental blend with smoky incense and sweet vanilla undertones.",
    ingredients: ["Incense", "Clove", "Vanilla", "Amber"]
  },

  {
    id: 11,
    brand: "Amber",
    name: "Amber Gold",
    price: 130,
    fragrance: "Woody",
    img: "/Pic/Amber/pic002.jpg",
    discount: null,
    quantity: 10, 
    description: "Rich amber layered with earthy woods, a scent of strength and warmth.",
    ingredients: ["Amber resin", "Oak", "Cedar", "Vetiver"]
  },
  {
    id: 12,
    brand: "mera",
    name: "Mera Shine",
    price: 30,
    fragrance: "Floral",
    img: "/Pic/mera/pic003.jpg",
    discount: null,
    quantity: 10, 
    description: "A luminous floral fragrance with delicate notes of gardenia and rose.",
    ingredients: ["Gardenia", "Rose", "Jasmine", "Musk"]
  },
  {
    id: 13,
    brand: "The LAB",
    name: "Lab Fresh",
    price: 100,
    fragrance: "Fresh",
    img: "/Pic/The_Lab_pic/pic004.jpg",
    discount: null,
    quantity: 10,
    description: "Refreshing blend of citrus and herbs, crafted for clarity and energy.",
    ingredients: ["Lime", "Mint", "Rosemary", "Sea salt"]
  },
  {
    id: 14,
    brand: "Amber",
    name: "Amber Essence",
    price: 20,
    fragrance: "Woody",
    img: "/Pic/Amber/pic005.jpg",
    discount: 50,
    quantity: 10, 
    description: "Amber infused with smoky woods, a bold yet elegant fragrance.",
    ingredients: ["Amber resin", "Sandalwood", "Oud", "Spices"]
  },
  {
    id: 15,
    brand: "BOSBA SCENT",
    name: "Bosba Bloom",
    price: 85,
    fragrance: "Floral",
    img: "/Pic/Bosba Scent/pic001.jpg",
    discount: null,
    quantity: 10, 
    description: "Blooming floral notes of rose and jasmine, soft and romantic.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 16,
    brand: "BOSBA SCENT",
    name: "Lab Classic",
    price: 150,
    fragrance: "Fresh",
    img: "/Pic/Bosba Scent/pic002.jpg",
    discount: null,
    quantity: 10, 
    description: "Classic fresh tones with citrus and green accords, timeless and clean.",
    ingredients: ["Lemon", "Green tea", "Mint", "Musk"]
  },
  {
    id: 17,
    brand: "BOSBA SCENT",
    name: "Romyana Pure",
    price: 15,
    fragrance: "Citrus",
    img: "/Pic/Bosba Scent/pic003.jpg",
    discount: null,
    quantity: 10, 
    description: "Pure citrus blend with sparkling zest, lively and refreshing.",
    ingredients: ["Orange", "Grapefruit", "Lime", "Cedarwood"]
  },
  {
    id: 18,
    brand: "BOSBA SCENT",
    name: "Bosba Mist",
    price: 110,
    fragrance: "Oriental",
    img: "/Pic/Bosba Scent/pic004.jpg",
    discount: 20,
    quantity: 10, 
    description: "Oriental mist with exotic spices and resins, mysterious and alluring.",
    ingredients: ["Cardamom", "Patchouli", "Vanilla", "Amber"]
  },
  {
    id: 19,
    brand: "BOSBA SCENT",
    name: "Bosba Gold",
    price: 130,
    fragrance: "Woody",
    img: "/Pic/Bosba Scent/pic005.jpg",
    discount: null,
    quantity: 10, 
    description: "Golden amber with smoky woods, a timeless scent of sophistication.",
    ingredients: ["Amber resin", "Oud", "Sandalwood", "Tonka bean"]
  },
  {
    id: 20,
    brand: "BOSBA SCENT",
    name: "Bosba Shine",
    price: 90,
    fragrance: "Floral",
    img: "/Pic/Bosba Scent/pic006.jpg",
    discount: null,
    quantity: 10, 
    description: "Radiant floral fragrance with sparkling notes of lily and peony.",
    ingredients: ["Lily", "Peony", "Rose water", "White musk"]
  },
  {
    id: 21,
    brand: "BOSBA SCENT",
    name: "Mera Shine",
    price: 40,
    fragrance: "Floral",
    img: "/Pic/Bosba Scent/pic007.jpg",
    discount: 10,
    quantity: 10, 
    description: "Radiant floral fragrance with sparkling notes of lily and peony.",
    ingredients: ["Lily", "Peony", "Rose water", "White musk"]
  },
    {
    id: 22,
    brand: "BOSBA SCENT",
    name: "bosba Essence",
    price: 120,
    fragrance: "Woody",
    img: "/Pic/Bosba Scent/pic008.jpg",
    discount: 50,
    quantity: 10,
    description: "A warm woody fragrance that blends amber with subtle spice, evoking elegance and depth.",
    ingredients: ["Amber resin", "Sandalwood", "Cedar", "Spices"]
  },
  {
    id: 23,
    brand: "Amber",
    name: "Amber Bloom",
    price: 85,
    fragrance: "Floral",
    img: "/Pic/Amber/pic003.jpg",
    discount: null,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 24,
    brand: "Amber",
    name: "Amber Bloom",
    price: 50,
    fragrance: "Floral",
    img: "/Pic/Amber/pic004.jpg",
    discount: null,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 25,
    brand: "Amber",
    name: "Amber Bloom",
    price: 100,
    fragrance: "Floral",
    img: "/Pic/Amber/pic005.jpg",
    discount: 20,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 26,
    brand: "Amber",
    name: "Amber Bloom",
    price: 65,
    fragrance: "Floral",
    img: "/Pic/Amber/pic006.jpg",
    discount: null,
    quantity: 0, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },

  {
    id: 27,
    brand: "Amber",
    name: "Amber Bloom",
    price: 185,
    fragrance: "Floral",
    img: "/Pic/Amber/pic007.jpg",
    discount: null,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 28,
    brand: "Amber",
    name: "Amber Bloom",
    price: 25,
    fragrance: "Floral",
    img: "/Pic/Amber/pic008.jpg",
    discount: null,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 29,
    brand: "Amber",
    name: "Amber Bloom",
    price: 15,
    fragrance: "Floral",
    img: "/Pic/Amber/pic009.jpg",
    discount: null,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
 {
    id: 30,
    brand: "Amber",
    name: "Amber Bloom",
    price: 15,
    fragrance: "Floral",
    img: "/Pic/Amber/pic010.jpg",
    discount: null,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 31,
    brand: "Amber",
    name: "Amber Bloom",
    price: 65,
    fragrance: "Floral",
    img: "/Pic/Amber/pic011.jpg",
    discount: null,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },

  {
    id: 32,
    brand: "Amber",
    name: "Amber Bloom",
    price: 35,
    fragrance: "Floral",
    img: "/Pic/Amber/pic012.jpg",
    discount: null,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 33,
    brand: "Amber",
    name: "Amber Bloom",
    price: 25,
    fragrance: "Floral",
    img: "/Pic/Amber/pic015.jpg",
    discount: 10,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 34,
    brand: "Amber",
    name: "Amber Bloom",
    price: 285,
    fragrance: "Floral",
    img: "/Pic/Amber/pic016.jpg",
    discount: 20,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 35,
    brand: "Amber",
    name: "Amber Bloom",
    price: 85,
    fragrance: "Floral",
    img: "/Pic/Amber/pic017.jpg",
    discount: 30,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 36,
    brand: "Amber",
    name: "Amber Bloom",
    price: 75,
    fragrance: "Floral",
    img: "/Pic/Amber/pic018.jpg",
    discount: 20,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 37,
    brand: "Amber",
    name: "Amber Bloom",
    price: 35,
    fragrance: "Floral",
    img: "/Pic/Amber/pic019.jpg",
    discount: null,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 38,
    brand: "Amber",
    name: "Amber Bloom",
    price: 85,
    fragrance: "Floral",
    img: "/Pic/Amber/pic020.jpg",
    discount: null,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 39,
    brand: "Amber",
    name: "Amber Bloom",
    price: 100,
    fragrance: "Floral",
    img: "/Pic/Amber/pic021.jpg",
    discount: 50,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 40,
    brand: "Amber",
    name: "Amber Bloom",
    price: 85,
    fragrance: "Floral",
    img: "/Pic/Amber/pic022.jpg",
    discount: 50,
    quantity: 0, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 41,
    brand: "mera",
    name: "Mera Shine",
    price: 90,
    fragrance: "Floral",
    img: "/Pic/mera/pic002.jpg",
    discount: null,
    quantity: 10, 
    description: "Radiant floral fragrance with sparkling notes of lily and peony.",
    ingredients: ["Lily", "Peony", "Rose water", "White musk"]
  },
  {
    id: 42,
    brand: "mera",
    name: "Mera Shine",
    price: 40,
    fragrance: "Floral",
    img: "/Pic/mera/pic003.jpg",
    discount: 20,
    quantity: 10, 
    description: "Radiant floral fragrance with sparkling notes of lily and peony.",
    ingredients: ["Lily", "Peony", "Rose water", "White musk"]
  },
   {
    id: 43,
    brand: "mera",
    name: "Mera Shine",
    price: 20,
    fragrance: "Floral",
    img: "/Pic/mera/pic004.jpg",
    discount: null,
    quantity: 10, 
    description: "Radiant floral fragrance with sparkling notes of lily and peony.",
    ingredients: ["Lily", "Peony", "Rose water", "White musk"]
  },
  {
    id: 44,
    brand: "mera",
    name: "Mera Bloom",
    price: 85,
    fragrance: "Floral",
    img: "/Pic/Amber/pic003.jpg",
    discount: null,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 45,
    brand: "The LAB",
    name: "Lab Classic",
    price: 150,
    fragrance: "Fresh",
    img: "/Pic/The_Lab_pic/pic004.jpg",
    discount: null,
    quantity: 0, 
    description: "A crisp fresh scent designed for modern minimalists, combining citrus and aquatic notes.",
    ingredients: ["Lemon zest", "Aquatic accord", "Green tea", "Musk"]
  },
  {
    id: 46,
    brand: "The LAB",
    name: "Lab Classic",
    price: 50,
    fragrance: "Fresh",
    img: "/Pic/The_Lab_pic/pic005.jpg",
    discount: 10,
    quantity: 10, 
    description: "A crisp fresh scent designed for modern minimalists, combining citrus and aquatic notes.",
    ingredients: ["Lemon zest", "Aquatic accord", "Green tea", "Musk"]
  },
  {
    id: 47,
    brand: "The LAB",
    name: "Lab Classic",
    price: 30,
    fragrance: "Fresh",
    img: "/Pic/The_Lab_pic/pic006.jpg",
    discount: 20,
    quantity: 20, 
    description: "A crisp fresh scent designed for modern minimalists, combining citrus and aquatic notes.",
    ingredients: ["Lemon zest", "Aquatic accord", "Green tea", "Musk"]
  },

  {
    id: 48,
    brand: "The LAB",
    name: "Lab Classic",
    price: 50,
    fragrance: "Fresh",
    img: "/Pic/The_Lab_pic/pic006.jpg",
    discount: null,
    quantity: 10, 
    description: "A crisp fresh scent designed for modern minimalists, combining citrus and aquatic notes.",
    ingredients: ["Lemon zest", "Aquatic accord", "Green tea", "Musk"]
  },
  {
    id: 49,
    brand: "The LAB",
    name: "Lab Classic",
    price: 50,
    fragrance: "Fresh",
    img: "/Pic/The_Lab_pic/pic007.jpg",
    discount: 15,
    quantity: 10, 
    description: "A crisp fresh scent designed for modern minimalists, combining citrus and aquatic notes.",
    ingredients: ["Lemon zest", "Aquatic accord", "Green tea", "Musk"]
  },
  {
    id: 50,
    brand: "The LAB",
    name: "Lab Classic",
    price: 150,
    fragrance: "Fresh",
    img: "/Pic/The_Lab_pic/pic008.jpg",
    discount: 50,
    quantity: 10, 
    description: "A crisp fresh scent designed for modern minimalists, combining citrus and aquatic notes.",
    ingredients: ["Lemon zest", "Aquatic accord", "Green tea", "Musk"]
  },
  {
    id: 52,
    brand: "The LAB",
    name: "Lab Classic",
    price: 59,
    fragrance: "Fresh",
    img: "/Pic/The_Lab_pic/pic009.jpg",
    discount: 10,
    quantity: 10, 
    description: "A crisp fresh scent designed for modern minimalists, combining citrus and aquatic notes.",
    ingredients: ["Lemon zest", "Aquatic accord", "Green tea", "Musk"]
  },
  {
    id: 52,
    brand: "The LAB",
    name: "Lab Classic",
    price: 250,
    fragrance: "Fresh",
    img: "/Pic/The_Lab_pic/pic010.jpg",
    discount: 10,
    quantity: 10, 
    description: "A crisp fresh scent designed for modern minimalists, combining citrus and aquatic notes.",
    ingredients: ["Lemon zest", "Aquatic accord", "Green tea", "Musk"]
  },

  {
    id: 53,
    brand: "The LAB",
    name: "Lab Classic",
    price: 25,
    fragrance: "Fresh",
    img: "/Pic/The_Lab_pic/pic011.jpg",
    discount: 10,
    quantity: 10, 
    description: "A crisp fresh scent designed for modern minimalists, combining citrus and aquatic notes.",
    ingredients: ["Lemon zest", "Aquatic accord", "Green tea", "Musk"]
  },
  {
    id: 54,
    brand: "The LAB",
    name: "Lab Classic",
    price: 50,
    fragrance: "Fresh",
    img: "/Pic/The_Lab_pic/pic012.jpg",
    discount: 10,
    quantity: 10, 
    description: "A crisp fresh scent designed for modern minimalists, combining citrus and aquatic notes.",
    ingredients: ["Lemon zest", "Aquatic accord", "Green tea", "Musk"]
  },
  {
    id: 55,
    brand: "The LAB",
    name: "Lab Fresh",
    price: 140,
    fragrance: "Fresh",
    img: "/Pic/The_Lab_pic/pic003.jpg",
    discount: null,
    quantity: 10,
    description: "Refreshing blend of citrus and herbs, crafted for clarity and energy.",
    ingredients: ["Lime", "Mint", "Rosemary", "Sea salt"]
  },
  {
    id: 56,
    brand: "Amber",
    name: "Amber Essence",
    price: 120,
    fragrance: "Woody",
    img: "/Pic/The_Lab_pic/pic004.jpg",
    discount: 50,
    quantity: 10, 
    description: "Amber infused with smoky woods, a bold yet elegant fragrance.",
    ingredients: ["Amber resin", "Sandalwood", "Oud", "Spices"]
  },
  {
    id: 57,
    brand: "mera",
    name: "Mera Bloom",
    price: 85,
    fragrance: "Floral",
    img: "/Pic/The_Lab_pic/pic005.jpg",
    discount: null,
    quantity: 10, 
    description: "Blooming floral notes of rose and jasmine, soft and romantic.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 58,
    brand: "The LAB",
    name: "Lab Classic",
    price: 150,
    fragrance: "Fresh",
    img: "/Pic/The_Lab_pic/pic006.jpg",
    discount: null,
    quantity: 10, 
    description: "Classic fresh tones with citrus and green accords, timeless and clean.",
    ingredients: ["Lemon", "Green tea", "Mint", "Musk"]
  },
  {
    id: 59,
    brand: "ROMYANA",
    name: "Romyana Pure",
    price: 95,
    fragrance: "Citrus",
    img: "/Pic/The_Lab_pic/pic007.jpg",
    discount: null,
    quantity: 10, 
    description: "Pure citrus blend with sparkling zest, lively and refreshing.",
    ingredients: ["Orange", "Grapefruit", "Lime", "Cedarwood"]
  },
  {
    id: 60,
    brand: "TARO",
    name: "Taro Mist",
    price: 110,
    fragrance: "Oriental",
    img: "/Pic/The_Lab_pic/pic008.jpg",
    discount: 20,
    quantity: 10, 
    description: "Oriental mist with exotic spices and resins, mysterious and alluring.",
    ingredients: ["Cardamom", "Patchouli", "Vanilla", "Amber"]
  },
  {
    id: 61,
    brand: "Amber",
    name: "Amber Gold",
    price: 130,
    fragrance: "Woody",
    img: "/Pic/The_Lab_pic/pic009.jpg",
    discount: null,
    quantity: 10, 
    description: "Golden amber with smoky woods, a timeless scent of sophistication.",
    ingredients: ["Amber resin", "Oud", "Sandalwood", "Tonka bean"]
  },
  {
    id: 62,
    brand: "mera",
    name: "Mera Shine",
    price: 90,
    fragrance: "Floral",
    img: "/Pic/The_Lab_pic/pic010.jpg",
    discount: null,
    quantity: 10, 
    description: "Radiant floral fragrance with sparkling notes of lily and peony.",
    ingredients: ["Lily", "Peony", "Rose water", "White musk"]
  },
  {
    id: 63,
    brand: "Amber",
    name: "Mera Shine",
    price: 90,
    fragrance: "Floral",
    img: "/Pic/The_Lab_pic/pic010.jpg",
    discount: null,
    quantity: 10, 
    description: "Radiant floral fragrance with sparkling notes of lily and peony.",
    ingredients: ["Lily", "Peony", "Rose water", "White musk"]
  },
];