export const products = [
  {
    id: 1,
    brand: "Amber",
    name: "Amber Essence",
    price: 120,
    fragrance: "Woody",
    img: "/Pic/Amber/pic001.jpg",
    discount: 50,
    quantity: 10,
    description: "A warm woody fragrance that blends amber with subtle spice, evoking elegance and depth.",
    ingredients: ["Amber resin", "Sandalwood", "Cedar", "Spices"]
  },
  {
    id: 2,
    brand: "mera",
    name: "Mera Bloom",
    price: 85,
    fragrance: "Floral",
    img: "/Pic/Amber/pic003.jpg",
    discount: null,
    quantity: 10, 
    description: "A soft floral bouquet that captures everyday beauty with notes of rose and jasmine.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 3,
    brand: "The LAB",
    name: "Lab Classic",
    price: 150,
    fragrance: "Fresh",
    img: "/Pic/Amber/pic004.jpg",
    discount: null,
    quantity: 0, 
    description: "A crisp fresh scent designed for modern minimalists, combining citrus and aquatic notes.",
    ingredients: ["Lemon zest", "Aquatic accord", "Green tea", "Musk"]
  },
  {
    id: 4,
    brand: "ROMYANA",
    name: "Romyana Pure",
    price: 95,
    fragrance: "Citrus",
    img: "/Pic/Amber/pic005.jpg",
    discount: null,
   quantity: 10, 
    description: "Bright citrus tones that energize and uplift, perfect for daily wear.",
    ingredients: ["Orange peel", "Grapefruit", "Lime", "Cedarwood"]
  },
  {
    id: 5,
    brand: "TARO",
    name: "Taro Mist",
    price: 110,
    fragrance: "Oriental",
    img: "/Pic/Amber/pic006.jpg",
    discount: 20,
    quantity: 10, 
    description: "An oriental mist with exotic spices and deep resins, evoking mystery and allure.",
    ingredients: ["Cardamom", "Patchouli", "Vanilla", "Amber"]
  },

  {
    id: 6,
    brand: "Amber",
    name: "Amber Gold",
    price: 130,
    fragrance: "Woody",
    img: "/Pic/De Scent/pic001.jpg",
    discount: null,
    quantity: 10, 
    description: "Golden amber enriched with smoky woods, a timeless scent of sophistication.",
    ingredients: ["Amber resin", "Oud", "Sandalwood", "Tonka bean"]
  },
  {
    id: 7,
    brand: "mera",
    name: "Mera Shine",
    price: 90,
    fragrance: "Floral",
    img: "/Pic/De Scent/pic002.jpg",
    discount: null,
    quantity: 10, 
    description: "A radiant floral fragrance with sparkling notes of lily and peony.",
    ingredients: ["Lily", "Peony", "Rose water", "White musk"]
  },
  {
    id: 8,
    brand: "The LAB",
    name: "Lab Fresh",
    price: 140,
    fragrance: "Fresh",
    img: "/Pic/De Scent/pic003.jpg",
    discount: null,
    quantity: 10, 
    description: "Clean and invigorating, blending crisp citrus with herbal freshness.",
    ingredients: ["Mint", "Basil", "Lemon", "Sea breeze accord"]
  },
  {
    id: 9,
    brand: "ROMYANA",
    name: "Romyana Pure",
    price: 95,
    fragrance: "Citrus",
    img: "/Pic/De Scent/pic004.jpg",
    discount: null,
    quantity: 10, 
    description: "Pure citrus harmony with a touch of sweetness, uplifting and bright.",
    ingredients: ["Mandarin", "Bergamot", "Neroli", "Vetiver"]
  },
  {
    id: 10,
    brand: "TARO",
    name: "Taro Mist",
    price: 110,
    fragrance: "Oriental",
    img: "/Pic/De Scent/pic005.jpg",
    discount: 20,
    quantity: 10, 
    description: "An oriental blend with smoky incense and sweet vanilla undertones.",
    ingredients: ["Incense", "Clove", "Vanilla", "Amber"]
  },

  {
    id: 11,
    brand: "Amber",
    name: "Amber Gold",
    price: 130,
    fragrance: "Woody",
    img: "/Pic/The_Lab_pic/pic001.jpg",
    discount: null,
    quantity: 10, 
    description: "Rich amber layered with earthy woods, a scent of strength and warmth.",
    ingredients: ["Amber resin", "Oak", "Cedar", "Vetiver"]
  },
  {
    id: 12,
    brand: "mera",
    name: "Mera Shine",
    price: 90,
    fragrance: "Floral",
    img: "/Pic/The_Lab_pic/pic002.jpg",
    discount: null,
    quantity: 10, 
    description: "A luminous floral fragrance with delicate notes of gardenia and rose.",
    ingredients: ["Gardenia", "Rose", "Jasmine", "Musk"]
  },
  {
    id: 13,
    brand: "The LAB",
    name: "Lab Fresh",
    price: 140,
    fragrance: "Fresh",
    img: "/Pic/The_Lab_pic/pic003.jpg",
    discount: null,
    quantity: 10,
    description: "Refreshing blend of citrus and herbs, crafted for clarity and energy.",
    ingredients: ["Lime", "Mint", "Rosemary", "Sea salt"]
  },
  {
    id: 14,
    brand: "Amber",
    name: "Amber Essence",
    price: 120,
    fragrance: "Woody",
    img: "/Pic/The_Lab_pic/pic004.jpg",
    discount: 50,
    quantity: 10, 
    description: "Amber infused with smoky woods, a bold yet elegant fragrance.",
    ingredients: ["Amber resin", "Sandalwood", "Oud", "Spices"]
  },
  {
    id: 15,
    brand: "mera",
    name: "Mera Bloom",
    price: 85,
    fragrance: "Floral",
    img: "/Pic/The_Lab_pic/pic005.jpg",
    discount: null,
    quantity: 10, 
    description: "Blooming floral notes of rose and jasmine, soft and romantic.",
    ingredients: ["Rose petals", "Jasmine", "Musk", "Citrus oils"]
  },
  {
    id: 16,
    brand: "The LAB",
    name: "Lab Classic",
    price: 150,
    fragrance: "Fresh",
    img: "/Pic/The_Lab_pic/pic006.jpg",
    discount: null,
    quantity: 10, 
    description: "Classic fresh tones with citrus and green accords, timeless and clean.",
    ingredients: ["Lemon", "Green tea", "Mint", "Musk"]
  },
  {
    id: 17,
    brand: "ROMYANA",
    name: "Romyana Pure",
    price: 95,
    fragrance: "Citrus",
    img: "/Pic/The_Lab_pic/pic007.jpg",
    discount: null,
    quantity: 10, 
    description: "Pure citrus blend with sparkling zest, lively and refreshing.",
    ingredients: ["Orange", "Grapefruit", "Lime", "Cedarwood"]
  },
  {
    id: 18,
    brand: "TARO",
    name: "Taro Mist",
    price: 110,
    fragrance: "Oriental",
    img: "/Pic/The_Lab_pic/pic008.jpg",
    discount: 20,
    quantity: 10, 
    description: "Oriental mist with exotic spices and resins, mysterious and alluring.",
    ingredients: ["Cardamom", "Patchouli", "Vanilla", "Amber"]
  },
  {
    id: 19,
    brand: "Amber",
    name: "Amber Gold",
    price: 130,
    fragrance: "Woody",
    img: "/Pic/The_Lab_pic/pic009.jpg",
    discount: null,
    quantity: 10, 
    description: "Golden amber with smoky woods, a timeless scent of sophistication.",
    ingredients: ["Amber resin", "Oud", "Sandalwood", "Tonka bean"]
  },
  {
    id: 20,
    brand: "mera",
    name: "Mera Shine",
    price: 90,
    fragrance: "Floral",
    img: "/Pic/The_Lab_pic/pic010.jpg",
    discount: null,
    quantity: 10, 
    description: "Radiant floral fragrance with sparkling notes of lily and peony.",
    ingredients: ["Lily", "Peony", "Rose water", "White musk"]
  },
  {
    id: 21,
    brand: "Amber",
    name: "Mera Shine",
    price: 90,
    fragrance: "Floral",
    img: "/Pic/The_Lab_pic/pic010.jpg",
    discount: null,
    quantity: 10, 
    description: "Radiant floral fragrance with sparkling notes of lily and peony.",
    ingredients: ["Lily", "Peony", "Rose water", "White musk"]
  },
];